services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - pvz_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9000:9000"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - pvz_network


volumes:
  postgresdb-data:
    driver: local

networks:
  pvz_network:
    name: pvz_network