services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - pvz_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - pvz_network

  main:
    depends_on:
      - db
      - prometheus
    container_name: mainService
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - '8080:8080'
      - '9000:9000'
    env_file:
      - ./.env
    networks:
      - pvz_network

  grpc:
    env_file:
      - ./.env
    container_name: grpcService
    build:
      context: .
      dockerfile: ./build/pvz.Dockerfile
    restart: always
    expose:
      - "8081:8081"
    ports:
      - '8081:8081'
    depends_on:
      - db
    networks:
      - pvz_network

volumes:
  postgresdb-data:
    driver: local

networks:
  pvz_network:
    name: pvz_network